[build]
  command = "npm run build"
  publish = "dist"

# Post-Processing komplett aus
[build.processing]
  skip_processing = true

# Falls du lieber nur JS-Optimierung ausmachst (Alternative):
#[build.processing.js]
#  bundle = false
#  minify = false
#  source_map = false
